# Changes here will be overwritten by Copier
_commit: v1.3.3
_src_path: gh:lincc-frameworks/python-project-template
author_email: mlg3k@uw.edu
author_name: Melissa L. Graham
create_example_module: true
custom_install: false
include_notebooks: true
module_name: image_utils
mypy_type_checking: none
preferred_linter: pylint
project_license: MIT
project_name: mlg_rubin_dp02_utils
use_gitlfs: none
use_isort: true
